HW2
================
Eric Xu
2025-09-23

to store the local data files, and use relative paths to access these
data files `"./Data/"`

## Problem 1

Data cleaning from csv files `snp` and `pol_month`, tidy and transpose
the `unemployment` file

``` r
pol_month = read_csv("./Data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon,sep = "-",
           into = c("year","month","day")) |> 
  mutate(
    year = as.integer(year),
    day = as.integer(day),
    month = as.integer(month),
    month = month.abb[month],
    president = case_when(prez_gop != 0 ~ "gop",
                          prez_dem != 0 ~ "dem")
    ) |> 
  select(-prez_gop, 
         -prez_dem, 
         -day
         )
snp = read_csv("./Data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date,
           sep = "/",
           into = c("month","day","year")) |> 
  mutate(
    year = as.integer(year),
    day = as.integer(day),
    month_num = as.integer(month),
    month = month.abb[month_num],
    year = case_when(
      year < 50 ~ 2000L + year,
      year >= 50 ~ 1900L + year
      )
    ) |> 
  select(year,month,everything()) |> 
  arrange(year,month_num)|> 
  select(-day,
         -month_num
         )

unemployment = read_csv("./Data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    values_to = "unemployment_rate",
    names_to = "month" 
    ) |> 
  rename(
    year = Year
  )
```

merge data with the same year and month variable:

``` r
joint = full_join(pol_month,snp, by = c("year","month")) |> 
  full_join(unemployment, by = c("year","month"))
```

**Descriptive data of `joint`:**

``` r
skimr::skim(joint)
```

|                                                  |       |
|:-------------------------------------------------|:------|
| Name                                             | joint |
| Number of rows                                   | 828   |
| Number of columns                                | 11    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |       |
| Column type frequency:                           |       |
| character                                        | 2     |
| numeric                                          | 9     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |       |
| Group variables                                  | None  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| month         |         0 |          1.00 |   3 |   3 |     0 |       12 |          0 |
| president     |         6 |          0.99 |   3 |   3 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| year | 0 | 1.00 | 1981.00 | 19.93 | 1947.00 | 1964.00 | 1981.00 | 1998.0 | 2015.00 | ▇▇▇▇▇ |
| gov_gop | 6 | 0.99 | 22.48 | 5.68 | 12.00 | 18.00 | 22.00 | 28.0 | 34.00 | ▆▆▇▅▅ |
| sen_gop | 6 | 0.99 | 46.10 | 6.38 | 32.00 | 42.00 | 46.00 | 51.0 | 56.00 | ▃▃▇▇▇ |
| rep_gop | 6 | 0.99 | 194.92 | 29.24 | 141.00 | 176.00 | 195.00 | 222.0 | 253.00 | ▃▇▆▃▅ |
| gov_dem | 6 | 0.99 | 27.20 | 5.94 | 17.00 | 22.00 | 28.00 | 32.0 | 41.00 | ▆▅▇▆▂ |
| sen_dem | 6 | 0.99 | 54.41 | 7.37 | 44.00 | 48.00 | 53.00 | 58.0 | 71.00 | ▇▆▇▃▂ |
| rep_dem | 6 | 0.99 | 244.97 | 31.37 | 188.00 | 211.00 | 250.00 | 268.0 | 301.00 | ▇▂▇▇▅ |
| close | 41 | 0.95 | 474.89 | 545.96 | 17.05 | 83.74 | 138.53 | 941.8 | 2107.39 | ▇▁▂▁▁ |
| unemployment_rate | 18 | 0.98 | 5.83 | 1.65 | 2.50 | 4.70 | 5.60 | 6.9 | 10.80 | ▃▇▅▂▁ |

``` r
names(joint)
```

    ##  [1] "year"              "month"             "gov_gop"          
    ##  [4] "sen_gop"           "rep_gop"           "gov_dem"          
    ##  [7] "sen_dem"           "rep_dem"           "president"        
    ## [10] "close"             "unemployment_rate"

``` r
joint |> 
  ggplot(aes(x = year, y = unemployment_rate, color = president)) +
  geom_point(na.rm = TRUE) +
  labs(
    title = "Average Monthly Unemployment Rate Over Time",
    y = "Unemployment Rate (%)",
    x = "Year"
  ) +
  scale_x_continuous(n.breaks = 10)+
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    axis.title = element_text(size = 14, ),
    axis.text = element_text(size = 12)
    )
```

![](p8105_hw2_sx2402_files/figure-gfm/plot%20and%20descriptive%20data-1.png)<!-- -->

``` r
joint |> 
  ggplot(aes(x = year, y = close, color = president)) +
  geom_point(na.rm = TRUE) +
  labs(
    title = "S&P Closing Value over Time",
    x = "Year",
    y = "closing Values S&P"
  ) +  
  scale_x_continuous(n.breaks = 10)+
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    axis.title = element_text(size = 14, ),
    axis.text = element_text(size = 12)
    )
```

![](p8105_hw2_sx2402_files/figure-gfm/plot%20and%20descriptive%20data-2.png)<!-- -->

The dataset `joint` combines information from `pols-month`, `snp`, and
`unemployment`. The original files tracked the partisan composition of
U.S. politics from 1947 to 2015, along with an indicator for the sitting
president. The `snp` file contained monthly closing values of the S&P
500 stock index from 1950 to 2015, the mean value is 474.8887404, with a
standard deviation of 545.9569797. while the unemployment file provided
national unemployment rates is 1948 to 2015 by month. After cleaning and
aligning by year and month, the merged dataset `joint` has 828 rows and
11 columns, covering the period 1947 to 2015. On average, unemployment
was 5.83%, S&P closing values ranged within 17.049999 and 2107.389893.
The overall diagram shows an increasing trend of unemployment rate and
S&P closing value. The colored president political party demonstrated a
fluctuation of closing value after 2000 and spiking of unemployment rate
after 1980 when president is GOP. This data only shows association by
time and president political party, and the association is not examined
by other covariates.

## Problem 2

``` r
mr_trash_wheel = readxl::read_excel("./Data/202409 Trash Wheel Collection Data.xlsx",sheet = "Mr. Trash Wheel", range = "A2:N653")|>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr",
    year = as.integer(year)
    )

prof_trash_wheel = readxl::read_excel("./Data/202409 Trash Wheel Collection Data.xlsx",sheet = "Professor Trash Wheel", range = "A2:M120")|>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Professor",
    year = as.integer(year)
    )

gwyn_trash_wheel =  readxl::read_excel("./Data/202409 Trash Wheel Collection Data.xlsx",sheet = "Gwynnda Trash Wheel", range = "A2:L265")|>
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Gwynnda",
    year = as.integer(year)
    )


all_wheel = bind_rows(mr_trash_wheel,prof_trash_wheel,gwyn_trash_wheel)

skimr::skim(all_wheel)
```

|                                                  |           |
|:-------------------------------------------------|:----------|
| Name                                             | all_wheel |
| Number of rows                                   | 1032      |
| Number of columns                                | 15        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |           |
| Column type frequency:                           |           |
| character                                        | 2         |
| numeric                                          | 12        |
| POSIXct                                          | 1         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |           |
| Group variables                                  | None      |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| month         |         0 |             1 |   3 |   9 |     0 |       14 |          0 |
| trash_wheel   |         0 |             1 |   2 |   9 |     0 |        3 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| dumpster | 0 | 1.00 | 245.85 | 187.85 | 1.00 | 86.00 | 199.00 | 393.25 | 651.00 | ▇▆▃▃▃ |
| year | 0 | 1.00 | 2019.84 | 2.90 | 2014.00 | 2018.00 | 2020.00 | 2022.00 | 2024.00 | ▅▆▅▇▆ |
| weight_tons | 0 | 1.00 | 3.04 | 0.79 | 0.61 | 2.54 | 3.08 | 3.55 | 5.62 | ▁▃▇▃▁ |
| volume_cubic_yards | 0 | 1.00 | 15.08 | 1.29 | 5.00 | 15.00 | 15.00 | 15.00 | 20.00 | ▁▁▁▇▁ |
| plastic_bottles | 1 | 1.00 | 2201.31 | 1634.80 | 0.00 | 980.00 | 1900.00 | 2900.00 | 9830.00 | ▇▆▁▁▁ |
| polystyrene | 1 | 1.00 | 1383.05 | 1813.67 | 0.00 | 230.00 | 640.00 | 2045.00 | 11528.00 | ▇▂▁▁▁ |
| cigarette_butts | 1 | 1.00 | 13295.92 | 23690.78 | 0.00 | 2800.00 | 4800.00 | 12000.00 | 310000.00 | ▇▁▁▁▁ |
| glass_bottles | 264 | 0.74 | 20.92 | 15.08 | 0.00 | 10.00 | 18.00 | 28.00 | 110.00 | ▇▃▁▁▁ |
| plastic_bags | 1 | 1.00 | 927.03 | 1388.81 | 0.00 | 220.00 | 470.00 | 1115.00 | 13450.00 | ▇▁▁▁▁ |
| wrappers | 118 | 0.89 | 2246.28 | 2638.16 | 0.00 | 900.00 | 1440.00 | 2580.00 | 20100.00 | ▇▁▁▁▁ |
| sports_balls | 381 | 0.63 | 13.98 | 9.96 | 0.00 | 6.00 | 12.00 | 20.00 | 56.00 | ▇▆▂▁▁ |
| homes_powered | 69 | 0.93 | 46.54 | 17.89 | 0.00 | 39.00 | 49.83 | 58.08 | 93.67 | ▂▂▇▅▁ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min | max | median | n_unique |
|:---|---:|---:|:---|:---|:---|---:|
| date | 0 | 1 | 2014-05-16 | 2024-06-11 | 2020-12-26 | 540 |

The combined Trash Wheel dataset contains 1032 dumpster-level
observations across Mr., Professor, and Gwynnda Trash Wheels. Variables
include dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered, trash_wheel, and
item-specific counts such as `cigarette_butts`, `plastic_bottles`, and
`sports_balls`. The variable `weight_tons` measures the amount of trash
collected per dumpster, while `sports_balls` counts the number of balls
collected at time, rounded to the nearest integer. Professor Trash Wheel
has collected a total of 246.74 tons of trash, while Gwynnda collected
18120 cigarette butts in June 2022.

## Problem 3
