---
title: "HW2"
author: "Eric Xu"
date: "2025-09-23"
output: github_document
---
to store the local data files, and use relative paths to access these data files
`"./Data/"`
```{r setup, include = FALSE}
library(tidyverse)
```

## Problem 1
Data cleaning from csv files `snp` and `pol_month`, tidy and transpose the `unemployment` file
```{r Problem 1 data cleaning,message = FALSE}
pol_month = read_csv("./Data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon,sep = "-",into = c("year","month","day")) |> 
  mutate(
    year = as.integer(year),
    day = as.integer(day),
    month = as.integer(month),
    month = month.name[month],
    president = case_when(prez_gop == 1 ~ "gop",
                          prez_dem == 1 ~ "dem")
    ) |> 
  select(-prez_gop, -prez_dem, -day)

snp = read_csv("./Data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date,sep = "/",into = c("month","day","year")) |> 
  mutate(
    year = as.integer(year),
    day = as.integer(day),
    month_num = as.integer(month),
    month = month.name[month_num],
    year = case_when(
      year < 50 ~ 2000L + year,
      year >= 50 ~ 1900L + year
    )) |> 
  select(year,month,everything()) |> 
  arrange((year),(month_num))|> 
  select(-day,-month_num)

unemployment = read_csv("./Data/unemployment.csv") |> 
  pivot_longer(Jan:Dec,values_to = "unemployment_rate",names_to = "month" ) |> 
  rename(
    year = Year
  )
```


